package wireproxy

import (
	"bufio"
	"bytes"
	"encoding/base64"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"sync"
	"text/template"
	"time"
)

// pacJSTemplate is the JavaScript PAC file template.
// Rules and exceptions are pre-escaped for safe embedding in JS string literals.
const pacJSTemplate = `// Generated by wireproxy-awg gfwlist2pac
// Updated: {{.Updated}}
var proxy = "{{.Proxy}}";
var direct = "DIRECT";

var exceptions = [
{{- range $i, $v := .Exceptions}}{{if $i}},
{{end}}  "{{$v}}"{{end}}
];

var rules = [
{{- range $i, $v := .Rules}}{{if $i}},
{{end}}  "{{$v}}"{{end}}
];

function matchRule(url, host, rule) {
    if (rule.length > 2 && rule[0] === '|' && rule[1] === '|') {
        var d = rule.substring(2);
        return host === d || host.slice(-(d.length + 1)) === '.' + d;
    }
    if (rule.length > 0 && rule[0] === '|') {
        return url.indexOf(rule.substring(1)) === 0;
    }
    if (rule.length > 1 && rule[0] === '/' && rule[rule.length - 1] === '/') {
        try { return (new RegExp(rule.slice(1, -1))).test(url); } catch(e) { return false; }
    }
    if (rule.length > 0 && rule[0] === '.') {
        return host === rule.substring(1) || host.slice(-rule.length) === rule;
    }
    return url.indexOf(rule) !== -1;
}

function FindProxyForURL(url, host) {
    for (var i = 0; i < exceptions.length; i++) {
        if (matchRule(url, host, exceptions[i])) return direct;
    }
    for (var i = 0; i < rules.length; i++) {
        if (matchRule(url, host, rules[i])) return proxy;
    }
    return direct;
}
`

type pacTemplateData struct {
	Updated    string
	Proxy      string
	Exceptions []string
	Rules      []string
}

// jsEscapeRule escapes a gfwlist rule string for safe embedding inside a
// JavaScript double-quoted string literal.
func jsEscapeRule(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// fetchFromSource downloads from an HTTP(S) URL or reads a local file.
func fetchFromSource(source string) ([]byte, error) {
	if strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://") {
		client := &http.Client{Timeout: 30 * time.Second}
		resp, err := client.Get(source)
		if err != nil {
			return nil, fmt.Errorf("download gfwlist: %w", err)
		}
		defer resp.Body.Close()
		return io.ReadAll(resp.Body)
	}
	return os.ReadFile(source)
}

// loadGFWList returns the raw GFWList bytes according to the following strategy:
//
//   - Local file path: read directly; cacheFile and forceRefresh are ignored.
//   - URL, forceRefresh=false: return cacheFile contents if the file exists,
//     otherwise download from the URL and write to cacheFile.
//   - URL, forceRefresh=true: always download from the URL and update cacheFile.
//
// If a download fails but a (possibly stale) cacheFile exists, it is used as
// a fallback so the PAC server keeps running.
func loadGFWList(source, cacheFile string, forceRefresh bool) ([]byte, error) {
	isURL := strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://")
	if !isURL {
		return os.ReadFile(source)
	}

	// Try disk cache first (unless caller demands a fresh copy)
	if !forceRefresh && cacheFile != "" {
		if data, err := os.ReadFile(cacheFile); err == nil {
			log.Printf("PAC: using cached GFWList from %s\n", cacheFile)
			return data, nil
		}
	}

	// Fetch from network
	log.Printf("PAC: downloading GFWList from %s\n", source)
	data, err := fetchFromSource(source)
	if err != nil {
		// Download failed — fall back to stale cache if available
		if cacheFile != "" {
			if cached, cerr := os.ReadFile(cacheFile); cerr == nil {
				log.Printf("PAC: download failed (%s), using stale cache %s\n", err, cacheFile)
				return cached, nil
			}
		}
		return nil, err
	}

	// Persist to cache
	if cacheFile != "" {
		if werr := os.WriteFile(cacheFile, data, 0o644); werr != nil {
			log.Printf("PAC: warning: could not write cache to %s: %s\n", cacheFile, werr)
		} else {
			log.Printf("PAC: GFWList cached to %s\n", cacheFile)
		}
	}
	return data, nil
}

// parseGFWList decodes (base64 if needed) and parses ABP-format GFWList content.
// Lines starting with '!' or '[' are skipped. Lines starting with '@@' become
// exception rules (the prefix is stripped). All other non-empty lines become
// proxy rules. Rule strings are escaped for embedding in JS string literals.
//
// Base64 detection: if the entire input (after trimming whitespace) successfully
// decodes as standard base64, the decoded bytes are used; otherwise the raw input
// is treated as plain ABP text. In practice real ABP files contain characters
// such as '|', '.', '@' and '[' that are not valid base64, so false positives
// are not a concern for realistic input.
func parseGFWList(data []byte) (rules, exceptions []string) {
	trimmed := strings.TrimSpace(string(data))
	decoded, err := base64.StdEncoding.DecodeString(trimmed)
	if err != nil {
		// Not base64 — treat as plain ABP text
		decoded = data
	}

	scanner := bufio.NewScanner(bytes.NewReader(decoded))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "!") || strings.HasPrefix(line, "[") {
			continue
		}
		if strings.HasPrefix(line, "@@") {
			exceptions = append(exceptions, jsEscapeRule(line[2:]))
		} else {
			rules = append(rules, jsEscapeRule(line))
		}
	}
	return
}

// loadExtraRules reads additional ABP-format rules from a plain-text file.
// Plain-text files are expected; base64-encoded files are also accepted
// (parseGFWList auto-detects the encoding).
func loadExtraRules(path string) (rules, exceptions []string, err error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("read extra rules %s: %w", path, err)
	}
	rules, exceptions = parseGFWList(data)
	return
}

// generatePAC renders a PAC JavaScript file from the given proxy string and rule lists.
func generatePAC(proxy string, rules, exceptions []string) (string, error) {
	tmpl, err := template.New("pac").Parse(pacJSTemplate)
	if err != nil {
		return "", err
	}
	data := pacTemplateData{
		Updated:    time.Now().UTC().Format(time.RFC3339),
		Proxy:      jsEscapeRule(proxy), // escape backslashes and double-quotes
		Rules:      rules,
		Exceptions: exceptions,
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// buildPAC assembles a complete PAC file for the given config.
//
//   - forceRefresh=true  → bypass disk cache and re-download from URL.
//   - forceRefresh=false → use disk cache when available (recommended at startup).
//
// ExtraRules are loaded fresh on every call and merged in-memory on top of the
// base GFWList. They are never written to CacheFile.
func buildPAC(config *PACConfig, forceRefresh bool) (string, error) {
	raw, err := loadGFWList(config.GFWList, config.CacheFile, forceRefresh)
	if err != nil {
		return "", fmt.Errorf("load gfwlist: %w", err)
	}

	rules, exceptions := parseGFWList(raw)

	// Merge extra rules: prepend so they take priority over the base list
	if config.ExtraRules != "" {
		extraRules, extraExceptions, err := loadExtraRules(config.ExtraRules)
		if err != nil {
			log.Printf("PAC: warning: %s\n", err)
		} else {
			rules = append(extraRules, rules...)
			exceptions = append(extraExceptions, exceptions...)
			log.Printf("PAC: merged %d extra rules, %d extra exceptions from %s\n",
				len(extraRules), len(extraExceptions), config.ExtraRules)
		}
	}

	pac, err := generatePAC(config.Proxy, rules, exceptions)
	if err != nil {
		return "", err
	}
	log.Printf("PAC: built — %d proxy rules, %d exception rules\n", len(rules), len(exceptions))
	return pac, nil
}

// SpawnRoutine starts a local HTTP server on localhost:Port that serves the
// generated PAC file at /proxy.pac.
//
// GFWList is fetched via the host network stack (not the VPN tunnel).
// If GFWList is a URL the list is automatically refreshed every 24 hours;
// the refresh always bypasses the cache and updates CacheFile.
func (config *PACConfig) SpawnRoutine(_ *VirtualTun) {
	var (
		mu         sync.RWMutex
		pacContent string
	)

	rebuild := func(forceRefresh bool) {
		pac, err := buildPAC(config, forceRefresh)
		if err != nil {
			log.Printf("PAC: build error: %s\n", err)
			return
		}
		mu.Lock()
		pacContent = pac
		mu.Unlock()
	}

	// Initial build — prefers the disk cache over a network round-trip
	rebuild(false)

	// Periodic refresh (URL sources only): force re-download every 24 h
	if strings.HasPrefix(config.GFWList, "http://") || strings.HasPrefix(config.GFWList, "https://") {
		go func() {
			ticker := time.NewTicker(24 * time.Hour)
			defer ticker.Stop()
			for range ticker.C {
				rebuild(true)
			}
		}()
	}

	mux := http.NewServeMux()

	mux.HandleFunc("/proxy.pac", func(w http.ResponseWriter, r *http.Request) {
		mu.RLock()
		content := pacContent
		mu.RUnlock()
		if content == "" {
			http.Error(w, "PAC not ready yet", http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Content-Type", "application/x-ns-proxy-autoconfig")
		w.Header().Set("Cache-Control", "no-cache")
		_, _ = fmt.Fprint(w, content)
	})

	// Redirect root → /proxy.pac for convenience
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/proxy.pac", http.StatusFound)
	})

	addr := config.BindAddress
	log.Printf("PAC: HTTP server listening on http://%s/proxy.pac\n", addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("PAC server error: %s\n", err)
	}
}
